backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Interviews"
    name: "interviews"
    folder: "src/interviews"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Boekenrug",
          name: "thumbnail",
          widget: "image",
          required: true,
        }
      - { label: "Foto", name: "cover", widget: "image", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Ondertitel (nodig?)", name: "description", widget: "string" }
      - { label: "Geinterviewde auteur(s)", name: "interviewee", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "interviews" }
  - label: "Schrijfsels"
    name: "schrijfsels"
    folder: "src/schrijfsels"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Zijn er tags nodig?", "Of niet?"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Contact"
        name: "contact"
        file: "src/contact/contact.md"
        fields:
          - { label: layout, name: layout, widget: hidden, default: "default" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
